// Auto-generated mapping of static text to filenames
export const STATIC_VOICE_LINES: Record<string, string> = {
 'Time to work. No excuses. Write down WHY you\'re here.': 'goggins_prime_intro.mp3',
 'Good. You showed up. That\'s more than most people do.': 'goggins_prime_encouragement.mp3',
 'Struggling? Good. That\'s where growth happens. Push through.': 'goggins_prime_struggle.mp3',
 'You set your intention. Now LIVE it. Let\'s go.': 'goggins_prime_success.mp3',
 'Engine\'s primed. Now it\'s time to hunt.': 'goggins_prime_transition.mp3',
 'Survey the battlefield. Know what you\'re up against.': 'goggins_scout_intro.mp3',
 'You\'re building the map. Most people just dive in blind.': 'goggins_scout_encouragement.mp3',
 'Confused? That means you\'re paying attention. Keep going.': 'goggins_scout_struggle.mp3',
 'Territory scouted. You know where the fight is.': 'goggins_scout_success.mp3',
 'You\'ve seen the terrain. Now find the targets.': 'goggins_scout_transition.mp3',
 'Look at these problems. These are your TARGETS. Study them.': 'goggins_preview_intro.mp3',
 'You\'re not solving yet. You\'re loading the gun.': 'goggins_preview_encouragement.mp3',
 'Don\'t understand the problem? PERFECT. Now you know what to hunt for.': 'goggins_preview_struggle.mp3',
 'Targets acquired. Now go get the knowledge to destroy them.': 'goggins_preview_success.mp3',
 'You know what mastery looks like. Time to build.': 'goggins_preview_transition.mp3',
 'Concept map time. Connect the dots. Find the RELATIONSHIPS.': 'goggins_build_intro.mp3',
 'Each connection you make is a weapon in your arsenal.': 'goggins_build_encouragement.mp3',
 'Can\'t find the connection? Dig deeper. It\'s there.': 'goggins_build_struggle.mp3',
 'Web is built. Your understanding is taking shape.': 'goggins_build_success.mp3',
 'Understanding built. Now prove you can USE it.': 'goggins_build_transition.mp3',
 'Theory is nothing without practice. Let\'s work problems.': 'goggins_apply_intro.mp3',
 'Struggle with the example. That\'s how you BURN it in.': 'goggins_apply_encouragement.mp3',
 'Wrong answer? Good information. Now you know where to improve.': 'goggins_apply_struggle.mp3',
 'You worked through it. That\'s how champions train.': 'goggins_apply_success.mp3',
 'Skills sharpening. Now lock them in permanently.': 'goggins_apply_transition.mp3',
 'Blank sheet. No notes. Show me what you ACTUALLY know.': 'goggins_retain_intro.mp3',
 'The struggle of recall is what makes memory permanent.': 'goggins_retain_encouragement.mp3',
 'Can\'t remember? THAT\'S the signal to your brain: STORE THIS.': 'goggins_retain_struggle.mp3',
 'You pulled it from memory. That\'s REAL knowledge.': 'goggins_retain_success.mp3',
 'Memory strengthened. One more challenge awaits.': 'goggins_retain_transition.mp3',
 'Final test. Can you APPLY this knowledge anywhere? Prove it.': 'goggins_master_intro.mp3',
 'Change the scenario. If you truly understand, you can adapt.': 'goggins_master_encouragement.mp3',
 'Getting tripped up? That\'s showing you where understanding is shallow.': 'goggins_master_struggle.mp3',
 'You can transfer knowledge. You EARNED this mastery.': 'goggins_master_success.mp3',
 'Mastery achieved. You did the work. Stay hard.': 'goggins_master_transition.mp3',
 'Take a breath. Before we begin, let\'s connect with your purpose.': 'sage_prime_intro.mp3',
 'Your intention is beautiful. It will guide your learning.': 'sage_prime_encouragement.mp3',
 'It\'s okay to be uncertain. Clarity comes through action.': 'sage_prime_struggle.mp3',
 'You\'ve planted the seed. Now let\'s nurture it together.': 'sage_prime_success.mp3',
 'With clear intention, we\'re ready to explore.': 'sage_prime_transition.mp3',
 'Let\'s gently survey what lies ahead. No pressure, just curiosity.': 'sage_scout_intro.mp3',
 'You\'re creating scaffolding for understanding. Wise approach.': 'sage_scout_encouragement.mp3',
 'Confusion is the beginning of wisdom. Embrace it.': 'sage_scout_struggle.mp3',
 'You\'ve seen the landscape. The path is becoming clear.': 'sage_scout_success.mp3',
 'With awareness of the whole, we can explore the parts.': 'sage_scout_transition.mp3',
 'Let\'s look at where this knowledge leads. What problems will you solve?': 'sage_preview_intro.mp3',
 'You\'re learning with purpose. That\'s rare and powerful.': 'sage_preview_encouragement.mp3',
 'These problems seem hard now. That\'s natural. You\'re not meant to solve them yet.': 'sage_preview_struggle.mp3',
 'You see the destination. The journey will be meaningful.': 'sage_preview_success.mp3',
 'Purpose clarified. Let\'s build understanding.': 'sage_preview_transition.mp3',
 'Now we weave connections. Each link brings deeper understanding.': 'sage_build_intro.mp3',
 'Every connection you make is a moment of insight.': 'sage_build_encouragement.mp3',
 'Some connections are subtle. Give them time to reveal themselves.': 'sage_build_struggle.mp3',
 'Your understanding is blooming. Beautiful work.': 'sage_build_success.mp3',
 'Understanding flows. Let\'s channel it into practice.': 'sage_build_transition.mp3',
 'Knowledge becomes wisdom through application. Let\'s practice.': 'sage_apply_intro.mp3',
 'Each attempt teaches you something. There are no failures here.': 'sage_apply_encouragement.mp3',
 'Mistakes are teachers in disguise. What did this one show you?': 'sage_apply_struggle.mp3',
 'You\'ve transformed understanding into skill. Well done.': 'sage_apply_success.mp3',
 'Skills developing. Let\'s strengthen your memory.': 'sage_apply_transition.mp3',
 'Close your eyes and reach inward. What do you truly remember?': 'sage_retain_intro.mp3',
 'Even partial recall strengthens memory. Every bit matters.': 'sage_retain_encouragement.mp3',
 'Forgetting is natural. It\'s pointing you toward what needs attention.': 'sage_retain_struggle.mp3',
 'You pulled knowledge from within. It\'s becoming part of you.': 'sage_retain_success.mp3',
 'Memories deepening. One final exploration awaits.': 'sage_retain_transition.mp3',
 'True mastery is flexible wisdom. Can you apply this anywhere?': 'sage_master_intro.mp3',
 'You\'re stretching your understanding. That\'s growth.': 'sage_master_encouragement.mp3',
 'Meeting your edges is where growth lives. Stay curious.': 'sage_master_struggle.mp3',
 'You\'ve achieved flexible understanding. This knowledge is truly yours.': 'sage_master_success.mp3',
 'Mastery attained. Carry this wisdom forward gently.': 'sage_master_transition.mp3',
 'Before we begin... why does this truly matter to you?': 'socratic_prime_intro.mp3',
 'Interesting. And what makes that reason important?': 'socratic_prime_encouragement.mp3',
 'What\'s making this difficult? What would make it clearer?': 'socratic_prime_struggle.mp3',
 'You\'ve defined your why. But... what does success look like?': 'socratic_prime_success.mp3',
 'With purpose established, what should we explore first?': 'socratic_prime_transition.mp3',
 'What do you notice as you survey this material?': 'socratic_scout_intro.mp3',
 'What patterns are emerging? What connects to what?': 'socratic_scout_encouragement.mp3',
 'What specifically is confusing? How might you find out?': 'socratic_scout_struggle.mp3',
 'What\'s the overall shape you\'re seeing now?': 'socratic_scout_success.mp3',
 'Knowing the territory... what problems might this solve?': 'socratic_scout_transition.mp3',
 'Looking at these problems... what would you need to know to solve them?': 'socratic_preview_intro.mp3',
 'What\'s similar between these problems? What varies?': 'socratic_preview_encouragement.mp3',
 'Which part feels most unclear? Start there.': 'socratic_preview_struggle.mp3',
 'Now you know what to hunt for. What\'s your strategy?': 'socratic_preview_success.mp3',
 'Target identified. How will you build understanding?': 'socratic_preview_transition.mp3',
 'How do these concepts relate? What connects them?': 'socratic_build_intro.mp3',
 'Why does A connect to B? What\'s the nature of that relationship?': 'socratic_build_encouragement.mp3',
 'If you had to explain this connection... how would you?': 'socratic_build_struggle.mp3',
 'Your map reveals relationships. What surprises you about it?': 'socratic_build_success.mp3',
 'Understanding mapped. But can you USE it?': 'socratic_build_transition.mp3',
 'Given what you now understand... how would you approach this problem?': 'socratic_apply_intro.mp3',
 'What\'s your reasoning here? Why this approach?': 'socratic_apply_encouragement.mp3',
 'Where did your solution diverge? What assumption was different?': 'socratic_apply_struggle.mp3',
 'You solved it. But why did that approach work?': 'socratic_apply_success.mp3',
 'Skills developing. But will you remember tomorrow?': 'socratic_apply_transition.mp3',
 'Without looking... what do you actually recall?': 'socratic_retain_intro.mp3',
 'Which parts came easily? Which required effort?': 'socratic_retain_encouragement.mp3',
 'What\'s blocking recall? How might you strengthen that path?': 'socratic_retain_struggle.mp3',
 'You retrieved it from memory. What made that possible?': 'socratic_retain_success.mp3',
 'Memory accessed. But is it flexible understanding?': 'socratic_retain_transition.mp3',
 'If conditions changed... how would your understanding adapt?': 'socratic_master_intro.mp3',
 'What\'s the underlying principle? How does it generalize?': 'socratic_master_encouragement.mp3',
 'Where does your model break down? What does that reveal?': 'socratic_master_struggle.mp3',
 'You can transfer knowledge. What makes that possible?': 'socratic_master_success.mp3',
 'True understanding demonstrated. What will you explore next?': 'socratic_master_transition.mp3',
 'Alright team! Let\'s get locked in! What are we playing for today?': 'coach_prime_intro.mp3',
 'That\'s what I\'m talking about! Great energy!': 'coach_prime_encouragement.mp3',
 'Hey, it\'s okay! Even the pros have off days. Shake it off!': 'coach_prime_struggle.mp3',
 'YES! We\'ve got our game plan! Let\'s EXECUTE!': 'coach_prime_success.mp3',
 'Warm-up complete! Time to scout the competition!': 'coach_prime_transition.mp3',
 'Let\'s check out the playbook! See what we\'re working with!': 'coach_scout_intro.mp3',
 'You\'re doing your homework! Champions prepare!': 'coach_scout_encouragement.mp3',
 'Tricky play? Let\'s break it down piece by piece!': 'coach_scout_struggle.mp3',
 'Playbook reviewed! You know the game now!': 'coach_scout_success.mp3',
 'Scouting complete! Let\'s see the practice problems!': 'coach_scout_transition.mp3',
 'Game film time! Let\'s see what winning looks like!': 'coach_preview_intro.mp3',
 'You\'re studying the competition! Smart player!': 'coach_preview_encouragement.mp3',
 'Tough opponent? That\'s what makes the win sweeter!': 'coach_preview_struggle.mp3',
 'You know what to practice! Let\'s get those reps in!': 'coach_preview_success.mp3',
 'Film studied! Time to hit the practice field!': 'coach_preview_transition.mp3',
 'Diagram time! Let\'s map out our plays!': 'coach_build_intro.mp3',
 'Every connection is a new play in your arsenal!': 'coach_build_encouragement.mp3',
 'Confused play? Run it again! Repetition is key!': 'coach_build_struggle.mp3',
 'Playbook looking SOLID! Great work!': 'coach_build_success.mp3',
 'Plays designed! Time for practice drills!': 'coach_build_transition.mp3',
 'Drill time! Let\'s work those reps! Muscle memory!': 'coach_apply_intro.mp3',
 'That\'s it! Smooth execution! Keep it up!': 'coach_apply_encouragement.mp3',
 'Fumble? No worries! Run it again! That\'s what practice is for!': 'coach_apply_struggle.mp3',
 'Clean execution! You\'re game-ready!': 'coach_apply_success.mp3',
 'Great practice! Time for the memory test!': 'coach_apply_transition.mp3',
 'Pop quiz! No playbook! Show me what you\'ve got!': 'coach_retain_intro.mp3',
 'Trust your training! You put in the work!': 'coach_retain_encouragement.mp3',
 'Can\'t remember? That\'s feedback! We know what to drill!': 'coach_retain_struggle.mp3',
 'YOU NAILED IT! That\'s championship memory!': 'coach_retain_success.mp3',
 'Memory locked in! Final challenge time!': 'coach_retain_transition.mp3',
 'Championship round! Can you adapt when the play breaks down?': 'coach_master_intro.mp3',
 'Improvise! True champions adapt on the fly!': 'coach_master_encouragement.mp3',
 'Getting pressured? Stay calm! Find the open lane!': 'coach_master_struggle.mp3',
 'MVP PERFORMANCE! You can handle ANYTHING!': 'coach_master_success.mp3',
 'Championship WON! Incredible work today!': 'coach_master_transition.mp3',
 'Hey! Ready to study? Let\'s figure out what we\'re tackling today.': 'buddy_prime_intro.mp3',
 'Nice! I like it. Solid plan.': 'buddy_prime_encouragement.mp3',
 'Hmm, not sure what to pick? Happens to me too. Let\'s brainstorm.': 'buddy_prime_struggle.mp3',
 'Cool, we\'ve got our mission. Let\'s do this!': 'buddy_prime_success.mp3',
 'Alright, plan set! Let\'s take a quick look at the material.': 'buddy_prime_transition.mp3',
 'Okay, let\'s skim through and see what\'s here. No deep reading yet!': 'buddy_scout_intro.mp3',
 'Oh that diagram looks important! Good catch.': 'buddy_scout_encouragement.mp3',
 'Yeah this section looks dense. We\'ll break it down later.': 'buddy_scout_struggle.mp3',
 'Nice overview! I think I see how this fits together.': 'buddy_scout_success.mp3',
 'Got the lay of the land. Let\'s peek at some practice problems?': 'buddy_scout_transition.mp3',
 'Let\'s see what kind of problems we\'ll need to solve...': 'buddy_preview_intro.mp3',
 'Ooh interesting problem. I see what they\'re asking.': 'buddy_preview_encouragement.mp3',
 'This one\'s tricky. But that\'s why we\'re studying, right?': 'buddy_preview_struggle.mp3',
 'Okay, now I know what we\'re aiming for. Let\'s learn this!': 'buddy_preview_success.mp3',
 'Targets identified! Time to build our concept map.': 'buddy_preview_transition.mp3',
 'Concept map time! My favorite part. Let\'s connect the dots.': 'buddy_build_intro.mp3',
 'Oh nice connection! That\'s a good one.': 'buddy_build_encouragement.mp3',
 'Hmm how do these connect... let me think...': 'buddy_build_struggle.mp3',
 'Looking good! This is really coming together.': 'buddy_build_success.mp3',
 'Map\'s done! Now let\'s practice some problems.': 'buddy_build_transition.mp3',
 'Practice time! Let\'s work through some examples together.': 'buddy_apply_intro.mp3',
 'You\'re getting it! I see the pattern too.': 'buddy_apply_encouragement.mp3',
 'Okay that step was tricky. Let\'s look at it again.': 'buddy_apply_struggle.mp3',
 'Nice! You figured it out. On to the next one?': 'buddy_apply_success.mp3',
 'Good practice session! Let\'s test our memory now.': 'buddy_apply_transition.mp3',
 'Memory check! Put away the notes. What do we remember?': 'buddy_retain_intro.mp3',
 'Hey that\'s pretty good! You remembered a lot.': 'buddy_retain_encouragement.mp3',
 'Blanking on that part too, honestly. Let\'s review it quick.': 'buddy_retain_struggle.mp3',
 'Wow, you recalled most of it! Memory\'s solid.': 'buddy_retain_success.mp3',
 'Memory\'s looking good! One more challenge?': 'buddy_retain_transition.mp3',
 'Final boss! Can we apply this to new situations?': 'buddy_master_intro.mp3',
 'Interesting take! That makes sense.': 'buddy_master_encouragement.mp3',
 'Hmm that\'s making me think too. Let\'s puzzle through it.': 'buddy_master_struggle.mp3',
 'You totally get this now! Mastery achieved!': 'buddy_master_success.mp3',
 'We crushed it! Great study session. Same time tomorrow?': 'buddy_master_transition.mp3'
};
