---
- name: Ensure AWS Secret exists for SensaPBL Configuration
  community.aws.aws_secret:
    name: "sensapbl/prod/config"
    state: present
    secret_type: 'string'
    secret: "{{ sensapbl_secrets | to_json }}"
    description: "Production configuration for SensaPBL Frontend"
  register: secret_creation

- name: Display Secret ARN
  debug:
    msg: "Secret created at {{ secret_creation.arn }}"
