branch-defaults:
  main:
    environment: sensapbl-backend-prod
global:
  application_name: sensapbl-backend
  default_ec2_keyname: null
  default_platform: Node.js 20
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
