"""
Query Concepts Lambda Handler

Provides paginated access to concepts stored in DynamoDB.
Supports filtering by tier for lazy loading in the frontend.
Also handles Subject Management (List & Delete).
"""
import json
import os
from typing import Any, Dict, List, Optional

import boto3
from boto3.dynamodb.conditions import Key, Attr

# Import shared utilities
from shared.utils import (
    api_response,
    parse_cursor,
    create_cursor,
    create_gsi1_pk,
    create_pk, 
    create_subject_sk,
    TIERS,
)

# Environment variables
CONCEPTS_TABLE = os.environ.get("CONCEPTS_TABLE", "sensapbl-concepts-dev")
ENVIRONMENT = os.environ.get("ENVIRONMENT", "dev")

# Default page size
DEFAULT_LIMIT = 25
MAX_LIMIT = 100

# AWS clients
dynamodb = boto3.resource("dynamodb")


def lambda_handler(event: Dict[str, Any], context: Any) -> Dict[str, Any]:
    """
    Main Lambda handler for concept queries and subject management
    
    Query Parameters:
    - action: 'get_concepts' (default), 'list_subjects', 'delete_subject'
    - userId: User ID (required)
    - sessionId: Session ID (required for get/delete)
    - tier: Filter by tier (optional: foundation, keystone, utility)
    - limit: Number of items per page
    - cursor: Pagination cursor
    """
    try:
        # Parse query parameters
        params = event.get("queryStringParameters", {}) or {}
        action = params.get("action", "get_concepts")
        user_id = params.get("userId")
        
        if not user_id:
            return api_response(400, {"error": "userId is required"})

        if action == "list_subjects":
            return handle_list_subjects(user_id)
            
        elif action == "delete_subject":
            session_id = params.get("sessionId")
            if not session_id:
                return api_response(400, {"error": "sessionId is required for deletion"})
            return handle_delete_subject(user_id, session_id)
            
        else:
            # Default: get_concepts
            session_id = params.get("sessionId")
            if not session_id:
                return api_response(400, {"error": "sessionId is required"})
            
            tier = params.get("tier")
            limit = min(int(params.get("limit", DEFAULT_LIMIT)), MAX_LIMIT)
            cursor = params.get("cursor")
            
            if tier and tier not in TIERS:
                return api_response(400, {"error": f"Invalid tier. Must be one of: {', '.join(TIERS)}"})
            
            concepts, next_cursor = query_concepts(
                user_id=user_id,
                session_id=session_id,
                tier=tier,
                limit=limit,
                cursor=cursor,
            )
            
            return api_response(200, {
                "concepts": concepts,
                "nextCursor": next_cursor,
                "hasMore": next_cursor is not None,
                "count": len(concepts),
            })
        
    except Exception as e:
        return api_response(500, {"error": str(e)})


def handle_list_subjects(user_id: str) -> Dict[str, Any]:
    """
    List all subjects generated by a specific user.
    """
    table = dynamodb.Table(CONCEPTS_TABLE)
    user_pk = f"USER#{user_id}"
    
    # Query for all items where PK = USER#{userId} and SK starts with SUBJECT#
    response = table.query(
        KeyConditionExpression=Key("PK").eq(user_pk) & Key("SK").begins_with("SUBJECT#")
    )
    
    subjects = []
    for item in response.get("Items", []):
        subjects.append({
            "sessionId": item.get("sessionId"),
            "subject": item.get("subject"),
            "conceptCount": int(item.get("conceptCount", 0)),
            "createdAt": int(item.get("createdAt", 0)),
            "expiresAt": int(item.get("expiresAt", 0)),
        })
        
    # Sort by createdAt desc
    subjects.sort(key=lambda x: x["createdAt"], reverse=True)
    
    return api_response(200, {
        "subjects": subjects,
        "count": len(subjects)
    })


def handle_delete_subject(user_id: str, session_id: str) -> Dict[str, Any]:
    """
    Securely delete a subject and all its concepts.
    Only allows deletion if the userId matches the PK.
    """
    table = dynamodb.Table(CONCEPTS_TABLE)
    
    # 1. Verify ownership & Existence by deleting metadata item
    # PK = USER#{userId}, SK = SUBJECT#{sessionId}
    # If this delete succeeds, we are authorized (since we constructed PK from userId)
    user_pk = f"USER#{user_id}"
    subject_sk = create_subject_sk(session_id)
    
    try:
        table.delete_item(
            Key={
                "PK": user_pk,
                "SK": subject_sk
            }
        )
    except Exception as e:
        return api_response(500, {"error": f"Failed to delete metadata: {str(e)}"})
    
    # 2. Query and Batch Delete all Concepts
    # PK = USER#{userId}#SESSION#{session_id}
    # We need to find all items in this partition to delete them
    concepts_pk = create_pk(user_id, session_id)
    
    # Iterate and delete
    # Note: Scans/Queries on partition key are efficient
    response = table.query(
        KeyConditionExpression=Key("PK").eq(concepts_pk)
    )
    
    items_to_delete = response.get("Items", [])
    
    # Batch delete context manager
    with table.batch_writer() as batch:
        for item in items_to_delete:
            batch.delete_item(
                Key={
                    "PK": item["PK"],
                    "SK": item["SK"]
                }
            )
            
    return api_response(200, {
        "status": "deleted",
        "sessionId": session_id,
        "itemsDeleted": len(items_to_delete) + 1 # +1 for metadata
    })


def query_concepts(
    user_id: str,
    session_id: str,
    tier: Optional[str] = None,
    limit: int = DEFAULT_LIMIT,
    cursor: Optional[str] = None,
) -> tuple[List[Dict[str, Any]], Optional[str]]:
    """
    Query concepts from DynamoDB with optional tier filtering
    Uses GSI for efficient tier-based queries
    """
    table = dynamodb.Table(CONCEPTS_TABLE)
    gsi1_pk = create_gsi1_pk(user_id, session_id)
    
    # Build query parameters
    query_params = {
        "IndexName": "tier-index",
        "KeyConditionExpression": "GSI1PK = :pk",
        "ExpressionAttributeValues": {":pk": gsi1_pk},
        "Limit": limit,
    }
    
    # Add tier filter if specified
    if tier:
        query_params["KeyConditionExpression"] += " AND begins_with(GSI1SK, :tier)"
        query_params["ExpressionAttributeValues"][":tier"] = f"TIER#{tier}"
    
    # Add pagination cursor
    exclusive_start_key = parse_cursor(cursor)
    if exclusive_start_key:
        query_params["ExclusiveStartKey"] = exclusive_start_key
    
    # Execute query
    response = table.query(**query_params)
    
    # Transform items to concept format
    concepts = [transform_item_to_concept(item) for item in response.get("Items", [])]
    
    # Create next cursor
    last_evaluated_key = response.get("LastEvaluatedKey")
    next_cursor = create_cursor(last_evaluated_key)
    
    return concepts, next_cursor


def transform_item_to_concept(item: Dict[str, Any]) -> Dict[str, Any]:
    """
    Transform DynamoDB item to concept format matching TypeScript types
    """
    return {
        "id": item.get("conceptId"),
        "name": item.get("name", "Unnamed"),
        "tier": item.get("tier", "foundation"),
        "stageId": item.get("stageId", "PREPARE"),
        "description": item.get("description", ""),
        "keyPoints": item.get("keyPoints", []),
        "prerequisiteWeight": float(item.get("prerequisiteWeight", 0.5)),
        "displayProperties": item.get("displayProperties", {}),
    }


# Health check endpoint for simple GET requests
def health_check(event: Dict[str, Any], context: Any) -> Dict[str, Any]:
    """Simple health check for Lambda"""
    return api_response(200, {"status": "healthy", "service": "query_concepts"})
