import type { CertEntry } from './types';

export const AWS_CERTS: CertEntry[] = [
  {
    id: 'clf-c02',
    name: 'AWS Certified Cloud Practitioner',
    code: 'CLF-C02',
    provider: 'AWS',
    level: 'Foundational',
    domains: [
      {
        name: 'Cloud Concepts',
        weight: 24,
        tasks: [
          'Define how the AWS Cloud enables pay-as-you-go pricing',
          'Define the benefits of high availability, elasticity, and agility in the AWS Cloud',
          'Compare and contrast trade-offs between CapEx and OpEx',
          'Identify design principles of the AWS Well-Architected Framework',
          'Identify best practices for cloud adoption strategies (for example, Cloud Adoption Framework)',
          'Identify the six R migration strategies (rehost, replatform, refactor, repurchase, retire, retain)',
          'Identify aspects of Total Cost of Ownership (TCO) for cloud migration',
          'Identify cost optimization opportunities using AWS tools (for example, rightsizing, Reserved Instances)',
        ],
      },
      {
        name: 'Security and Compliance',
        weight: 30,
        tasks: [
          'Describe the AWS shared responsibility model',
          'Describe the customer and AWS responsibilities for different service types',
          'Identify governance and compliance resources from AWS (for example, AWS Artifact, AWS Config)',
          'Describe AWS compliance requirements and security controls',
          'Identify actions that need to occur within an AWS account for security configuration',
          'Describe IAM features and components (for example, users, groups, roles, policies)',
          'Describe how to manage access using IAM Identity Center and AWS Organizations',
          'Describe security capabilities that AWS provides (for example, AWS Shield, AWS WAF, Amazon Inspector)',
          'Describe security resources available from AWS (for example, AWS Trusted Advisor, AWS Security Hub)',
          'Describe encryption options in AWS (for example, at rest, in transit, AWS KMS)',
        ],
      },
      {
        name: 'Cloud Technology and Services',
        weight: 34,
        tasks: [
          'Identify AWS Management Console, CLI, SDKs, and IaC tools (for example, CloudFormation)',
          'Identify different types of cloud deployment models (hybrid, all-in cloud, on-premises)',
          'Describe Regions, Availability Zones, and edge locations',
          'Describe how to achieve high availability using AWS global infrastructure',
          'Describe the benefits of Amazon CloudFront and AWS edge services',
          'Describe EC2 instance types and purchasing options (for example, On-Demand, Reserved, Spot)',
          'Describe AWS container services (for example, Amazon ECS, Amazon EKS, AWS Fargate)',
          'Describe AWS serverless compute services (for example, AWS Lambda)',
          'Describe AWS relational database services (for example, Amazon RDS, Amazon Aurora)',
          'Describe AWS non-relational database services (for example, Amazon DynamoDB)',
          'Describe VPC components and related services (for example, subnets, security groups, network ACLs)',
          'Describe Amazon Route 53 and DNS concepts',
          'Describe network connectivity options (for example, VPN, Direct Connect, VPC peering)',
          'Describe AWS block, object, and file storage services (for example, Amazon EBS, Amazon S3, Amazon EFS)',
          'Describe AWS storage migration services (for example, AWS DataSync, AWS Storage Gateway)',
          'Describe AI/ML services (for example, Amazon SageMaker, Amazon Rekognition, Amazon Comprehend)',
          'Describe analytics services (for example, Amazon Athena, Amazon Kinesis, AWS Glue, Amazon QuickSight)',
          'Describe application integration services (for example, Amazon SQS, Amazon SNS, AWS Step Functions)',
          'Describe management and governance services (for example, AWS CloudTrail, Amazon CloudWatch, AWS Systems Manager)',
        ],
      },
      {
        name: 'Billing, Pricing, and Support',
        weight: 12,
        tasks: [
          'Describe Reserved Instance, Savings Plans, Spot Instance, and On-Demand pricing models',
          'Describe data transfer charges and storage pricing tiers',
          'Describe AWS billing and cost management tools (for example, AWS Cost Explorer, AWS Budgets, AWS Cost and Usage Report)',
          'Describe AWS Organizations consolidated billing',
          'Describe AWS Support plans and features (for example, Basic, Developer, Business, Enterprise)',
          'Describe AWS Trusted Advisor and AWS Health Dashboard',
        ],
      },
    ],
  },
  {
    id: 'aif-c01',
    name: 'AWS Certified AI Practitioner',
    code: 'AIF-C01',
    provider: 'AWS',
    level: 'Foundational',
    domains: [
      {
        name: 'Fundamentals of AI and ML',
        weight: 20,
        tasks: [
          'Explain basic AI concepts and terminologies',
          'Identify practical use cases for AI',
          'Describe the ML development lifecycle',
          'Distinguish predictive AI from generative AI scenarios',
          'Identify criteria for selecting AWS AI and ML services',
        ],
      },
      {
        name: 'Fundamentals of Generative AI',
        weight: 24,
        tasks: [
          'Explain the basic concepts of generative AI',
          'Understand the capabilities and limitations of generative AI for solving business problems',
          'Describe AWS generative AI services',
          'Describe prompt design fundamentals and grounding strategies',
          'Identify quality and safety risks in generative AI outputs',
        ],
      },
      {
        name: 'Applications of Foundation Models',
        weight: 28,
        tasks: [
          'Describe design considerations for foundation model applications',
          'Choose effective prompt engineering techniques',
          'Describe the training and fine-tuning process for foundation models',
          'Describe methods to evaluate foundation model performance',
        ],
      },
      {
        name: 'Guidelines for Responsible AI',
        weight: 14,
        tasks: [
          'Explain the development of AI systems that are responsible',
          'Recognize the importance of transparent and explainable models',
          'Identify bias, fairness, and accountability controls for AI systems',
        ],
      },
      {
        name: 'Security, Compliance, and Governance for AI Solutions',
        weight: 14,
        tasks: [
          'Explain methods to secure AI systems',
          'Recognize governance and compliance regulations for AI systems',
          'Describe data protection and model access control patterns for AI workloads',
        ],
      },
    ],
  },
  {
    id: 'dva-c02',
    name: 'AWS Certified Developer - Associate',
    code: 'DVA-C02',
    provider: 'AWS',
    level: 'Associate',
    domains: [
      {
        name: 'Development with AWS Services',
        weight: 32,
        tasks: [
          'Create fault-tolerant and resilient applications in a programming language (for example, Java, C#, Python, JavaScript, TypeScript, Go)',
          'Create, extend, and maintain APIs (for example, response/request transformations, enforcement of validation rules, overriding status codes)',
          'Write and run unit tests in development environments (for example, using AWS SAM)',
          'Write code to use messaging services (for example, Amazon SQS, Amazon SNS)',
          'Write code that interacts with AWS services by using APIs and AWS SDKs',
          'Handle data streaming by using AWS services (for example, Kinesis)',
          'Configure Lambda functions by defining environment variables and parameters (for example, memory, concurrency, timeout, runtime, handler, layers, extensions, triggers, destinations)',
          'Handle the event lifecycle and errors by using code (for example, Lambda Destinations, dead letter queues)',
          'Write and run test code by using AWS services and tools (for example, CodeBuild, AWS SAM, Lambda)',
          'Integrate Lambda functions with AWS services',
          'Tune Lambda functions for optimal performance',
          'Serialize and deserialize data to provide persistence to a data store',
          'Use, manage, and maintain data stores (for example, DynamoDB, S3)',
          'Manage data lifecycles',
          'Use data caching services (for example, ElastiCache, DAX)',
        ],
      },
      {
        name: 'Security',
        weight: 26,
        tasks: [
          'Use an identity provider to implement federated access (for example, Amazon Cognito, AWS IAM Identity Center)',
          'Secure applications by using bearer tokens',
          'Configure programmatic access to AWS',
          'Make authenticated calls to AWS services',
          'Assume an IAM role',
          'Define permissions for principals',
          'Use encryption keys to encrypt or decrypt data',
          'Generate certificates and SSH keys for development purposes',
          'Use encryption across account boundaries',
          'Enable and disable key rotation',
          'Encrypt environment variables that contain sensitive data',
          'Use secret management services to secure sensitive data (for example, AWS Secrets Manager, AWS Systems Manager Parameter Store)',
          'Sanitize sensitive data',
        ],
      },
      {
        name: 'Deployment',
        weight: 24,
        tasks: [
          'Manage the dependencies of the code module (for example, environment variables, configuration files, container images)',
          'Package the application to be deployed to AWS',
          'Manage container images',
          'Write and run integration tests',
          'Make API calls using endpoints from different stages',
          'Test code by creating mock environments',
          'Configure automated testing in CI/CD pipelines',
          'Perform application deployment using existing compute resources',
          'Implement canary, blue/green, or rolling deployment strategies',
          'Update existing IaC templates (for example, AWS SAM, CloudFormation)',
        ],
      },
      {
        name: 'Troubleshooting and Optimization',
        weight: 18,
        tasks: [
          'Debug code to identify defects',
          'Interpret application metrics, logs, and traces',
          'Query logs to find relevant data',
          'Implement custom metrics (for example, CloudWatch embedded metric format)',
          'Implement an effective logging strategy to record application behavior and state',
          'Implement code that emits custom metrics',
          'Add annotations for tracing services (for example, AWS X-Ray)',
          'Implement notification alerts for relevant actions (for example, Amazon SNS, CloudWatch alarms)',
          'Profile application performance',
          'Determine minimum memory and compute power for an application',
          'Use subscription filter policies to optimize messaging',
          'Cache content based on request headers',
        ],
      },
    ],
  },
  {
    id: 'soa-c03',
    name: 'AWS Certified CloudOps Engineer - Associate',
    code: 'SOA-C03',
    provider: 'AWS',
    level: 'Associate',
    domains: [
      {
        name: 'Monitoring, Logging, Analysis, Remediation, and Performance Optimization',
        weight: 20,
        tasks: [
          'Implement metrics, alarms, and filters by using AWS monitoring and logging services',
          'Remediate issues based on monitoring and availability metrics',
          'Optimize performance and cost based on metrics and data',
        ],
      },
      {
        name: 'Reliability and Business Continuity',
        weight: 16,
        tasks: [
          'Implement scalability and elasticity based on use case',
          'Implement high availability and resilient environments',
          'Implement backup and restore strategies',
          'Validate disaster recovery readiness through recovery testing',
        ],
      },
      {
        name: 'Deployment, Provisioning, and Automation',
        weight: 18,
        tasks: [
          'Provision and maintain cloud resources',
          'Automate manual or repeatable processes',
          'Implement policy-driven infrastructure provisioning controls',
        ],
      },
      {
        name: 'Security and Compliance',
        weight: 16,
        tasks: [
          'Implement and manage security and compliance policies',
          'Implement data and infrastructure protection strategies',
          'Operate continuous compliance monitoring and reporting workflows',
        ],
      },
      {
        name: 'Networking and Content Delivery',
        weight: 18,
        tasks: [
          'Implement networking features and connectivity',
          'Configure domains, DNS services, and content delivery',
          'Troubleshoot network connectivity issues',
        ],
      },
    ],
  },
  {
    id: 'saa-c03',
    name: 'AWS Certified Solutions Architect - Associate',
    code: 'SAA-C03',
    provider: 'AWS',
    level: 'Associate',
    domains: [
      {
        name: 'Design Secure Architectures',
        weight: 30,
        tasks: [
          'Apply AWS security best practices to IAM users and root users (for example, multi-factor authentication [MFA])',
          'Design a flexible authorization model that includes IAM users, groups, roles, and policies',
          'Design a role-based access control strategy (for example, AWS STS, role switching, cross-account access)',
          'Design a security strategy for multiple AWS accounts (for example, AWS Control Tower, service control policies [SCPs])',
          'Determine the appropriate use of resource policies for AWS services',
          'Determine when to federate a directory service with IAM roles',
          'Design VPC architectures with security components (for example, security groups, route tables, network ACLs, NAT gateways)',
          'Determine network segmentation strategies (for example, using public subnets and private subnets)',
          'Integrate AWS services to secure applications (for example, AWS Shield, AWS WAF, IAM Identity Center, AWS Secrets Manager)',
          'Secure external network connections to and from the AWS Cloud (for example, VPN, AWS Direct Connect)',
          'Align AWS technologies to meet compliance requirements',
          'Encrypt data at rest (for example, AWS Key Management Service [AWS KMS])',
          'Encrypt data in transit (for example, AWS Certificate Manager [ACM] using TLS)',
          'Implement access policies for encryption keys',
          'Implement data backups and replications',
          'Implement policies for data access, lifecycle, and protection',
          'Rotate encryption keys and renew certificates',
        ],
      },
      {
        name: 'Design Resilient Architectures',
        weight: 26,
        tasks: [
          'Design event-driven, microservice, and/or multi-tier architectures based on requirements',
          'Determine scaling strategies for components used in an architecture design',
          'Determine the AWS services required to achieve loose coupling based on requirements',
          'Determine when to use containers',
          'Determine when to use serverless technologies and patterns',
          'Recommend appropriate compute, storage, networking, and database technologies based on requirements',
          'Use purpose-built AWS services for workloads',
          'Determine automation strategies to ensure infrastructure integrity',
          'Determine the AWS services required to provide a highly available and/or fault-tolerant architecture across AWS Regions or Availability Zones',
          'Identify metrics based on business requirements to deliver a highly available solution',
          'Implement designs to mitigate single points of failure',
          'Implement strategies to ensure the durability and availability of data (for example, backups)',
          'Select an appropriate DR strategy to meet business requirements',
          'Use AWS services that improve the reliability of legacy applications and applications not built for the cloud',
        ],
      },
      {
        name: 'Design High-Performing Architectures',
        weight: 24,
        tasks: [
          'Determine storage services and configurations that meet performance demands',
          'Determine storage services that can scale to accommodate future needs',
          'Decouple workloads so that components can scale independently',
          'Identify metrics and conditions to perform scaling actions',
          'Select the appropriate compute options and features (for example, EC2 instance types) to meet business requirements',
          'Select the appropriate resource type and size (for example, the amount of Lambda memory) to meet business requirements',
          'Configure read replicas to meet business requirements',
          'Design database architectures',
          'Determine an appropriate database engine (for example, MySQL compared with PostgreSQL)',
          'Determine an appropriate database type (for example, Amazon Aurora, Amazon DynamoDB)',
          'Integrate caching to meet business requirements',
          'Create a network topology for various architectures (for example, global, hybrid, multi-tier)',
          'Determine network configurations that can scale to accommodate future needs',
          'Determine the appropriate placement of resources to meet business requirements',
          'Select the appropriate load balancing strategy',
          'Build and secure data lakes',
          'Design data streaming architectures',
          'Design data transfer solutions',
          'Implement visualization strategies',
          'Select appropriate compute options for data processing (for example, Amazon EMR)',
          'Select appropriate configurations for ingestion',
          'Transform data between formats (for example, .csv to .parquet)',
        ],
      },
      {
        name: 'Design Cost-Optimized Architectures',
        weight: 20,
        tasks: [
          'Design appropriate storage strategies (for example, batch uploads to Amazon S3 compared with individual uploads)',
          'Determine the correct storage size for a workload',
          'Determine the lowest cost method of transferring data for a workload to AWS storage',
          'Determine when storage auto scaling is required',
          'Manage S3 object lifecycles',
          'Select the appropriate backup and/or archival solution',
          'Select the appropriate service for data migration to storage services',
          'Select the appropriate storage tier',
          'Select the correct data lifecycle for storage',
          'Select the most cost-effective storage service for a workload',
          'Determine an appropriate load balancing strategy (for example, ALB Layer 7 compared with NLB Layer 4 compared with Gateway Load Balancer)',
          'Determine appropriate scaling methods and strategies for elastic workloads (for example, horizontal compared with vertical, EC2 hibernation)',
          'Determine cost-effective AWS compute services with appropriate use cases (for example, Lambda, Amazon EC2, Fargate)',
          'Determine the required availability for different classes of workloads (for example, production workloads, non-production workloads)',
          'Select the appropriate instance family for a workload',
          'Select the appropriate instance size for a workload',
          'Design appropriate backup and retention policies (for example, snapshot frequency)',
          'Determine cost-effective AWS database services with appropriate use cases (for example, DynamoDB compared with Amazon RDS, serverless)',
          'Determine cost-effective AWS database types (for example, time series format, columnar format)',
          'Migrate database schemas and data to different locations and/or different database engines',
          'Configure appropriate NAT gateway types for a network (for example, a single shared NAT gateway compared with NAT gateways for each Availability Zone)',
          'Configure appropriate network connections (for example, Direct Connect compared with VPN compared with internet)',
          'Configure appropriate network routes to minimize network transfer costs (for example, Region to Region, Availability Zone to Availability Zone, private to public, Global Accelerator, VPC endpoints)',
          'Determine strategic needs for content delivery networks (CDNs) and edge caching',
          'Review existing workloads for network optimizations',
          'Select an appropriate throttling strategy',
          'Select the appropriate bandwidth allocation for a network device (for example, a single VPN compared with multiple VPNs, Direct Connect speed)',
        ],
      },
    ],
  },
  {
    id: 'mla-c01',
    name: 'AWS Certified Machine Learning Engineer - Associate',
    code: 'MLA-C01',
    provider: 'AWS',
    level: 'Associate',
    domains: [
      {
        name: 'Data Preparation for Machine Learning',
        weight: 28,
        tasks: [
          'Ingest and store data',
          'Transform data and perform feature engineering',
          'Ensure data integrity and prepare data for ML',
          'Implement data quality validation for training and inference datasets',
        ],
      },
      {
        name: 'ML Model Development',
        weight: 26,
        tasks: [
          'Choose a modeling approach',
          'Train and refine models',
          'Analyze and evaluate models',
          'Select metrics aligned to business and model risk requirements',
        ],
      },
      {
        name: 'Deployment and Orchestration of ML Workflows',
        weight: 22,
        tasks: [
          'Select deployment infrastructure based on existing architecture and requirements',
          'Create and script infrastructure based on existing architecture and requirements',
          'Use automated orchestration tools to set up continuous integration and continuous delivery (CI/CD) pipelines',
        ],
      },
      {
        name: 'ML Solution Monitoring, Maintenance, and Security',
        weight: 24,
        tasks: [
          'Monitor model performance and data quality',
          'Recommend improvements to ML solution performance',
          'Implement security practices for ML solutions',
          'Detect drift and trigger remediation workflows for model reliability',
        ],
      },
    ],
  },
  {
    id: 'dea-c01',
    name: 'AWS Certified Data Engineer - Associate',
    code: 'DEA-C01',
    provider: 'AWS',
    level: 'Associate',
    domains: [
      {
        name: 'Data Ingestion and Transformation',
        weight: 34,
        tasks: [
          'Perform data ingestion',
          'Transform and process data',
          'Orchestrate data pipelines',
          'Determine data layout, schema, structure, and format',
        ],
      },
      {
        name: 'Data Store Management',
        weight: 26,
        tasks: [
          'Choose a data store',
          'Understand data cataloging systems',
          'Manage the lifecycle of data',
        ],
      },
      {
        name: 'Data Operations and Support',
        weight: 22,
        tasks: [
          'Automate data processing by using AWS services',
          'Analyze data by using AWS services',
          'Maintain and monitor data pipelines',
          'Ensure data quality',
        ],
      },
      {
        name: 'Data Security and Governance',
        weight: 18,
        tasks: [
          'Apply authentication mechanisms',
          'Apply authorization mechanisms',
          'Ensure data encryption and masking',
          'Prepare logs for audit',
          'Understand data privacy and governance',
        ],
      },
    ],
  },
  {
    id: 'aip-c01',
    name: 'AWS Certified Generative AI Developer - Professional',
    code: 'AIP-C01',
    provider: 'AWS',
    level: 'Professional',
    domains: [
      {
        name: 'Foundation Model Integration, Data Management, and Compliance',
        weight: 24,
        tasks: [
          'Select and configure foundation models for specific use cases',
          'Determine data requirements for foundation model customization',
          'Apply compliance and governance standards to generative AI applications',
        ],
      },
      {
        name: 'Implementation and Integration',
        weight: 28,
        tasks: [
          'Develop applications using Amazon Bedrock and other generative AI services',
          'Implement retrieval augmented generation (RAG) solutions',
          'Develop agentic solutions using foundation models',
        ],
      },
      {
        name: 'AI Safety, Security, and Governance',
        weight: 16,
        tasks: [
          'Implement guardrails for generative AI applications',
          'Apply security best practices to generative AI solutions',
          'Implement governance frameworks for AI systems',
        ],
      },
      {
        name: 'Operational Efficiency and Optimization for GenAI Applications',
        weight: 18,
        tasks: [
          'Optimize foundation model inference performance',
          'Implement cost optimization strategies for generative AI workloads',
          'Monitor and troubleshoot generative AI applications',
        ],
      },
      {
        name: 'Testing, Validation, and Troubleshooting',
        weight: 14,
        tasks: [
          'Design and implement testing strategies for generative AI applications',
          'Validate model outputs and application behavior',
          'Troubleshoot generative AI application issues',
        ],
      },
    ],
  },
  {
    id: 'sap-c02',
    name: 'AWS Certified Solutions Architect - Professional',
    code: 'SAP-C02',
    provider: 'AWS',
    level: 'Professional',
    domains: [
      {
        name: 'Design Solutions for Organizational Complexity',
        weight: 26,
        tasks: [
          'Architect network connectivity strategies',
          'Prescribe security controls',
          'Design reliable and resilient architectures',
          'Design a multi-account AWS environment',
          'Determine cost optimization and visibility strategies',
        ],
      },
      {
        name: 'Design for New Solutions',
        weight: 29,
        tasks: [
          'Design a deployment strategy to meet business requirements',
          'Design a solution to ensure business continuity',
          'Determine security controls based on requirements',
          'Design a strategy to meet reliability requirements',
          'Design a solution to meet performance objectives',
          'Determine a cost optimization strategy to meet solution goals and objectives',
        ],
      },
      {
        name: 'Continuous Improvement for Existing Solutions',
        weight: 25,
        tasks: [
          'Determine a strategy to improve overall operational excellence',
          'Determine a strategy to improve security',
          'Determine a strategy to improve performance',
          'Determine a strategy to improve reliability',
          'Identify opportunities for cost optimizations',
        ],
      },
      {
        name: 'Accelerate Workload Migration and Modernization',
        weight: 20,
        tasks: [
          'Select existing workloads and processes for potential migration',
          'Determine the optimal migration approach for existing workloads',
          'Determine a new architecture design for existing workloads',
          'Determine opportunities for modernization and enhancements',
        ],
      },
    ],
  },
  {
    id: 'dop-c02',
    name: 'AWS Certified DevOps Engineer - Professional',
    code: 'DOP-C02',
    provider: 'AWS',
    level: 'Professional',
    domains: [
      {
        name: 'SDLC Automation',
        weight: 22,
        tasks: [
          'Implement CI/CD pipelines',
          'Integrate automated testing into CI/CD pipelines',
          'Build and manage artifacts',
          'Implement deployment strategies',
        ],
      },
      {
        name: 'Configuration Management and IaC',
        weight: 17,
        tasks: [
          'Define cloud infrastructure and reusable components to provision and manage systems throughout their lifecycle',
          'Deploy automation to create, update, and delete infrastructure',
          'Implement service and infrastructure configuration management',
        ],
      },
      {
        name: 'Resilient Cloud Solutions',
        weight: 15,
        tasks: [
          'Implement highly available solutions',
          'Implement solutions that are scalable to accommodate changing workloads',
          'Implement automated recovery processes',
        ],
      },
      {
        name: 'Monitoring and Logging',
        weight: 15,
        tasks: [
          'Configure the collection, aggregation, and storage of logs and metrics',
          'Audit, monitor, and analyze logs and metrics to detect issues',
          'Automate monitoring and event management of complex environments',
        ],
      },
      {
        name: 'Incident and Event Response',
        weight: 14,
        tasks: [
          'Manage event sources to process, notify, and take action in response to events',
          'Implement configuration changes in response to events',
          'Troubleshoot issues and determine remediation steps',
        ],
      },
      {
        name: 'Security and Compliance',
        weight: 17,
        tasks: [
          'Implement techniques for identity and access management at scale',
          'Apply automated security controls to manage sensitive data and credentials',
          'Implement compliance validation and audit strategies',
        ],
      },
    ],
  },
  {
    id: 'mls-c01',
    name: 'AWS Certified Machine Learning - Specialty',
    code: 'MLS-C01',
    provider: 'AWS',
    level: 'Specialty',
    domains: [
      {
        name: 'Data Engineering',
        weight: 20,
        tasks: [
          'Create data repositories for ML',
          'Identify and implement a data ingestion solution',
          'Identify and implement a data transformation solution',
        ],
      },
      {
        name: 'Exploratory Data Analysis',
        weight: 24,
        tasks: [
          'Sanitize and prepare data for modeling',
          'Perform feature engineering',
          'Analyze and visualize data for ML',
        ],
      },
      {
        name: 'Modeling',
        weight: 36,
        tasks: [
          'Frame business problems as ML problems',
          'Select the appropriate model(s) for a given ML problem',
          'Train ML models',
          'Perform hyperparameter optimization',
          'Evaluate ML models',
        ],
      },
      {
        name: 'Machine Learning Implementation and Operations',
        weight: 20,
        tasks: [
          'Build ML solutions for performance, availability, scalability, resiliency, and fault tolerance',
          'Recommend and implement the appropriate ML services and features for a given problem',
          'Apply basic AWS security practices to ML solutions',
          'Deploy and operationalize ML solutions',
        ],
      },
    ],
  },
  {
    id: 'scs-c03',
    name: 'AWS Certified Security - Specialty',
    code: 'SCS-C03',
    provider: 'AWS',
    level: 'Specialty',
    domains: [
      {
        name: 'Detection',
        weight: 16,
        tasks: [
          'Design and implement monitoring and alerting for an AWS account or organization',
          'Design and implement logging',
          'Troubleshoot security monitoring, logging and alerting',
        ],
      },
      {
        name: 'Incident Response',
        weight: 14,
        tasks: [
          'Design and test an incident response plan',
          'Respond to security events',
          'Perform containment, eradication, and recovery actions in cloud incidents',
        ],
      },
      {
        name: 'Infrastructure Security',
        weight: 18,
        tasks: [
          'Design, implement, and troubleshoot security controls for network edge services',
          'Design, implement, and troubleshoot security controls for compute workloads',
          'Design and troubleshoot network security controls',
        ],
      },
      {
        name: 'Identity and Access Management',
        weight: 20,
        tasks: [
          'Design, implement, and troubleshoot authentication strategies',
          'Design, implement, and troubleshoot authorization strategies',
          'Implement privileged access controls and federation patterns',
        ],
      },
      {
        name: 'Data Protection',
        weight: 18,
        tasks: [
          'Design and implement controls for data in transit',
          'Design and implement controls for data at rest',
          'Design and implement controls to protect confidential data, credentials, secrets, and cryptographic key materials',
        ],
      },
      {
        name: 'Security Foundations and Governance',
        weight: 14,
        tasks: [
          'Develop a strategy to centrally deploy and manage AWS accounts',
          'Implement a secure and consistent deployment strategy for cloud resources',
          'Evaluate the compliance of AWS resources',
        ],
      },
    ],
  },
  {
    id: 'ans-c01',
    name: 'AWS Certified Advanced Networking - Specialty',
    code: 'ANS-C01',
    provider: 'AWS',
    level: 'Specialty',
    domains: [
      {
        name: 'Network Design',
        weight: 30,
        tasks: [
          'Design a solution that incorporates edge network services to optimize user performance and traffic management for global architectures',
          'Design DNS solutions that meet public, private, and hybrid requirements',
          'Design solutions that integrate load balancing to meet high availability, scalability, and security requirements',
          'Define logging and monitoring requirements across AWS and hybrid networks',
          'Design a routing strategy and connectivity architecture between on-premises networks and the AWS Cloud',
          'Design a routing strategy and connectivity architecture that include multiple AWS accounts, AWS Regions, and VPCs to support different connectivity patterns',
        ],
      },
      {
        name: 'Network Implementation',
        weight: 26,
        tasks: [
          'Implement routing and connectivity between on-premises networks and the AWS Cloud',
          'Implement routing and connectivity across multiple AWS accounts, Regions, and VPCs to support different connectivity patterns',
          'Implement complex hybrid and multi-account DNS architectures',
          'Automate and configure network infrastructure',
        ],
      },
      {
        name: 'Network Management and Operation',
        weight: 20,
        tasks: [
          'Maintain routing and connectivity on AWS and hybrid networks',
          'Monitor and analyze network traffic to troubleshoot and optimize connectivity patterns',
          'Optimize AWS networks for performance, reliability, and cost-effectiveness',
        ],
      },
      {
        name: 'Network Security, Compliance, and Governance',
        weight: 24,
        tasks: [
          'Implement and maintain network features to meet security and compliance needs and requirements',
          'Validate and audit security by using network monitoring and logging services',
          'Implement and maintain confidentiality of data and communications of the network',
        ],
      },
    ],
  },
];
