import type { CertEntry } from './types';

export const CISCO_CERTS: CertEntry[] = [
  {
    id: 'cisco-ccna-200-301',
    name: 'Cisco Certified Network Associate',
    code: '200-301',
    provider: 'Cisco',
    level: 'Associate',
    domains: [
      {
        name: 'Network Fundamentals',
        weight: 20,
        tasks: [
          'Explain the role and function of network components (routers, L2/L3 switches, firewalls, IPS, access points, controllers, endpoints, servers, PoE)',
          'Describe characteristics of network topology architectures (two-tier, three-tier, spine-leaf, WAN, SOHO, on-premises and cloud)',
          'Compare physical interface and cabling types (single-mode fiber, multimode fiber, copper, connections)',
          'Identify interface and cable issues (collisions, errors, mismatch duplex, speed)',
          'Compare TCP to UDP',
          'Configure and verify IPv4 addressing and subnetting',
          'Describe the need for private IPv4 addressing',
          'Configure and verify IPv6 addressing and prefix',
          'Describe IPv6 address types (unicast, multicast, anycast, link-local)',
          'Verify IP parameters for client OS (Windows, Mac OS, Linux)',
        ],
      },
      {
        name: 'Network Access',
        weight: 20,
        tasks: [
          'Configure and verify VLANs (normal range) spanning multiple switches',
          'Configure and verify interswitch connectivity (trunk ports, 802.1Q, native VLAN)',
          'Configure and verify Layer 2 discovery protocols (CDP and LLDP)',
          'Configure and verify (Layer 2/Layer 3) EtherChannel (LACP)',
          'Interpret basic operations of Rapid PVST+ Spanning Tree Protocol',
          'Describe Cisco Wireless Architectures and AP modes',
          'Describe physical infrastructure connections of WLAN components (AP, WLC)',
          'Describe AP and WLC management access connections (Telnet, SSH, HTTP, HTTPS, console, TACACS+/RADIUS)',
          'Interpret the wireless LAN GUI configuration for client connectivity (WLAN creation, security settings, QoS profiles)',
        ],
      },
      {
        name: 'IP Connectivity',
        weight: 25,
        tasks: [
          'Interpret the components of a routing table (routing protocol code, prefix, network mask, next hop, administrative distance, metric, gateway of last resort)',
          'Determine how a router makes a forwarding decision by default (longest prefix match, administrative distance, routing protocol metric)',
          'Configure and verify IPv4 and IPv6 static routing (default route, network route, host route, floating static)',
          'Configure and verify single area OSPFv2 (neighbor adjacencies, point-to-point, broadcast, router ID, passive interface, default route advertisement)',
          'Describe the purpose, functions, and concepts of first hop redundancy protocols',
        ],
      },
      {
        name: 'IP Services',
        weight: 10,
        tasks: [
          'Configure and verify inside source NAT using static and pools',
          'Configure and verify NTP operating in a client and server mode',
          'Explain the role of DHCP and DNS within the network',
          'Explain the function of SNMP in network operations',
          'Describe the use of syslog features including facilities and levels',
          'Configure and verify DHCP client and relay',
          'Explain the forwarding per-hop behavior (PHB) for QoS (classification, marking, queuing, congestion, policing, shaping)',
          'Configure network devices for remote access using SSH',
          'Describe the capabilities and functions of TFTP/FTP in the network',
        ],
      },
      {
        name: 'Security Fundamentals',
        weight: 15,
        tasks: [
          'Define key security concepts (threats, vulnerabilities, exploits, mitigation techniques)',
          'Describe security program elements (user awareness, training, physical access control)',
          'Configure and verify device access control using local passwords',
          'Describe security password policy elements (management, complexity, password alternatives)',
          'Describe IPsec remote access and site-to-site VPNs',
          'Configure and verify access control lists',
          'Configure and verify Layer 2 security features (DHCP snooping, dynamic ARP inspection, port security)',
          'Compare authentication, authorization, and accounting concepts',
          'Describe wireless security protocols (WPA, WPA2, WPA3)',
          'Configure and verify WLAN within the GUI using WPA2 PSK',
        ],
      },
      {
        name: 'Automation and Programmability',
        weight: 10,
        tasks: [
          'Explain how automation impacts network management',
          'Compare traditional networks with controller-based networking',
          'Describe controller-based, software defined architecture (overlay, underlay, fabric)',
          'Compare traditional campus device management with Cisco DNA Center enabled device management',
          'Describe characteristics of REST-based APIs (CRUD, HTTP verbs, data encoding)',
          'Recognize the capabilities of configuration management mechanisms (Puppet, Chef, Ansible)',
          'Recognize components of JSON-encoded data',
        ],
      },
    ],
  },
  {
    id: 'cisco-ccnp-encor',
    name: 'Cisco CCNP Enterprise Core',
    code: '350-401 ENCOR',
    provider: 'Cisco',
    level: 'Professional',
    domains: [
      {
        name: 'Architecture',
        weight: 15,
        tasks: [
          'Explain the different design principles used in an enterprise network (high-level campus, WAN, data center, small office)',
          'Describe wireless network design principles (deployment models, location services)',
          'Explain the working principles of the Cisco SD-WAN solution',
          'Explain the working principles of the Cisco SD-Access solution',
          'Interpret wired and wireless QoS configurations',
          'Describe hardware and software switching mechanisms (process, CEF)',
        ],
      },
      {
        name: 'Virtualization',
        weight: 10,
        tasks: [
          'Describe device virtualization technologies (hypervisor type 1 and 2, virtual switching)',
          'Configure and verify data path virtualization technologies (VRF, GRE/IPsec tunneling)',
          'Describe network virtualization concepts (LISP, VXLAN)',
        ],
      },
      {
        name: 'Infrastructure',
        weight: 30,
        tasks: [
          'Configure and verify Layer 2 (VLANs, trunking, EtherChannel)',
          'Configure and verify Layer 3 (OSPFv2, EIGRP, BGP)',
          'Configure and verify IP services (NAT, NTP, DHCP, FHRP)',
          'Describe wireless principles (RF, antenna types, WLAN deployment)',
          'Describe and configure wireless security and client management',
          'Describe multicast protocols (IGMP, PIM)',
        ],
      },
      {
        name: 'Network Assurance',
        weight: 10,
        tasks: [
          'Diagnose network problems using tools (debugs, conditional debugs, trace, ping, SNMP, syslog)',
          'Configure and verify Flexible NetFlow',
          'Configure and verify SPAN/RSPAN/ERSPAN',
          'Configure and verify IPSLA',
          'Describe Cisco DNA Center workflows to apply network configuration, monitoring, and management',
          'Configure and verify NETCONF and RESTCONF',
        ],
      },
      {
        name: 'Security',
        weight: 20,
        tasks: [
          'Configure and verify device access control (lines, local user authentication and authorization)',
          'Configure and verify infrastructure security features (ACLs, CoPP)',
          'Describe REST API security',
          'Configure and verify wireless security features (EAP, WebAuth, PSK, MAB)',
          'Describe the components of network security design (threat defense, endpoint security, next-gen firewall, TrustSec, MACsec, network access control)',
        ],
      },
      {
        name: 'Automation',
        weight: 15,
        tasks: [
          'Interpret basic Python components and scripts',
          'Construct valid JSON-encoded files',
          'Describe the high-level principles and benefits of a data modeling language (YANG)',
          'Describe APIs for Cisco DNA Center and vManage',
          'Interpret REST API response codes and results in payload using Cisco DNA Center and RESTCONF',
          'Construct an EEM applet to automate configuration, troubleshooting, or data collection',
          'Compare agent vs. agentless orchestration tools (Chef, Puppet, Ansible, SaltStack)',
        ],
      },
    ],
  },
];
