import type { CertEntry } from './types';

export const ISC2_CERTS: CertEntry[] = [
  {
    id: 'isc2-cc',
    name: 'ISC2 Certified in Cybersecurity',
    code: 'CC',
    provider: 'ISC2',
    level: 'Foundational',
    domains: [
      {
        name: 'Security Principles',
        weight: 26,
        tasks: [
          'Discuss the foundational concepts of cybersecurity principles',
          'Define risk management terminology and summarize the process',
          'Relate risk management to personal or professional practices',
          'Classify types of security controls',
          'Distinguish between policies, procedures, standards, regulations, and laws',
        ],
      },
      {
        name: 'Business Continuity, Disaster Recovery, and Incident Response',
        weight: 10,
        tasks: [
          'Summarize the components of a business continuity (BC) plan',
          'Summarize the components of a disaster recovery (DR) plan',
          'Practice the terminology and components of incident response',
        ],
      },
      {
        name: 'Access Controls Concepts',
        weight: 22,
        tasks: [
          'Select appropriate access controls',
          'Describe the concepts behind access control models and physical access controls',
          'Describe logical access controls',
        ],
      },
      {
        name: 'Network Security',
        weight: 24,
        tasks: [
          'Understand computer networking',
          'Understand network threats and attacks',
          'Understand network security infrastructure',
        ],
      },
      {
        name: 'Security Operations',
        weight: 18,
        tasks: [
          'Understand data security',
          'Understand system hardening',
          'Understand best practice security policies',
          'Understand security awareness training',
        ],
      },
    ],
  },
  {
    id: 'isc2-sscp',
    name: 'ISC2 Systems Security Certified Practitioner',
    code: 'SSCP',
    provider: 'ISC2',
    level: 'Associate',
    domains: [
      {
        name: 'Security Operations and Administration',
        weight: 16,
        tasks: [
          'Comply with codes of ethics',
          'Understand security concepts',
          'Document, implement, and maintain functional security controls',
          'Participate in asset management',
          'Implement security controls and assess compliance',
          'Participate in change management',
          'Participate in security awareness and training',
        ],
      },
      {
        name: 'Access Controls',
        weight: 15,
        tasks: [
          'Implement and maintain authentication methods',
          'Support internetwork trust architectures',
          'Participate in the identity management lifecycle',
          'Implement access controls',
        ],
      },
      {
        name: 'Risk Identification, Monitoring, and Analysis',
        weight: 15,
        tasks: [
          'Understand the risk management process',
          'Perform security assessment activities',
          'Operate and maintain monitoring systems',
          'Analyze monitoring results',
        ],
      },
      {
        name: 'Incident Response and Recovery',
        weight: 13,
        tasks: [
          'Support incident lifecycle',
          'Understand and support forensic investigations',
          'Understand and support business continuity plan and disaster recovery plan activities',
        ],
      },
      {
        name: 'Cryptography',
        weight: 10,
        tasks: [
          'Understand fundamental concepts of cryptography',
          'Understand reasons and requirements for cryptography',
          'Understand and support secure protocols',
          'Understand public key infrastructure systems',
        ],
      },
      {
        name: 'Network and Communications Security',
        weight: 16,
        tasks: [
          'Understand and apply fundamental concepts of networking',
          'Understand network attacks and countermeasures',
          'Manage network access controls',
          'Manage network security',
          'Operate and configure network-based security devices',
          'Operate and configure wireless technologies',
        ],
      },
      {
        name: 'Systems and Application Security',
        weight: 15,
        tasks: [
          'Identify and analyze malicious code and activity',
          'Implement and operate endpoint device security',
          'Operate and configure cloud security',
          'Operate and secure virtual environments',
        ],
      },
    ],
  },
  {
    id: 'isc2-cissp',
    name: 'ISC2 Certified Information Systems Security Professional',
    code: 'CISSP',
    provider: 'ISC2',
    level: 'Expert',
    domains: [
      {
        name: 'Security and Risk Management',
        weight: 15,
        tasks: [
          'Understand, adhere to, and promote professional ethics',
          'Understand and apply security concepts',
          'Evaluate and apply security governance principles',
          'Determine compliance and other requirements',
          'Understand legal and regulatory issues that pertain to information security in a holistic context',
          'Understand requirements for investigation types',
          'Develop, document, and implement security policy, standards, procedures, and guidelines',
          'Identify, analyze, and prioritize business continuity requirements',
          'Contribute to and enforce personnel security policies and procedures',
          'Understand and apply risk management concepts',
          'Understand and apply threat modeling concepts and methodologies',
          'Apply supply chain risk management concepts',
          'Establish and maintain a security awareness, education, and training program',
        ],
      },
      {
        name: 'Asset Security',
        weight: 10,
        tasks: [
          'Identify and classify information and assets',
          'Establish information and asset handling requirements',
          'Provision resources securely',
          'Manage data lifecycle',
          'Ensure appropriate asset retention',
          'Determine data security controls and compliance requirements',
        ],
      },
      {
        name: 'Security Architecture and Engineering',
        weight: 13,
        tasks: [
          'Research, implement, and manage engineering processes using secure design principles',
          'Understand the fundamental concepts of security models',
          'Select controls based upon systems security requirements',
          'Understand security capabilities of information systems',
          'Assess and mitigate the vulnerabilities of security architectures, designs, and solution elements',
          'Select and determine cryptographic solutions',
          'Understand methods of cryptanalytic attacks',
          'Apply security principles to site and facility design',
          'Design site and facility security controls',
        ],
      },
      {
        name: 'Communication and Network Security',
        weight: 13,
        tasks: [
          'Assess and implement secure design principles in network architectures',
          'Secure network components',
          'Implement secure communication channels according to design',
        ],
      },
      {
        name: 'Identity and Access Management (IAM)',
        weight: 13,
        tasks: [
          'Control physical and logical access to assets',
          'Manage identification and authentication of people, devices, and services',
          'Federated identity with a third-party service',
          'Implement and manage authorization mechanisms',
          'Manage the identity and access provisioning lifecycle',
          'Implement authentication systems',
        ],
      },
      {
        name: 'Security Assessment and Testing',
        weight: 12,
        tasks: [
          'Design and validate assessment, test, and audit strategies',
          'Conduct security control testing',
          'Collect security process data',
          'Analyze test output and generate report',
          'Conduct or facilitate security audits',
        ],
      },
      {
        name: 'Security Operations',
        weight: 13,
        tasks: [
          'Understand and comply with investigations',
          'Conduct logging and monitoring activities',
          'Perform configuration management',
          'Apply foundational security operations concepts',
          'Apply resource protection',
          'Conduct incident management',
          'Operate and maintain detective and preventative measures',
          'Implement and support patch and vulnerability management',
          'Understand and participate in change management processes',
          'Implement recovery strategies',
          'Implement disaster recovery processes',
          'Test disaster recovery plans',
          'Participate in business continuity planning and exercises',
          'Implement and manage physical security',
          'Address personnel safety and security concerns',
        ],
      },
      {
        name: 'Software Development Security',
        weight: 11,
        tasks: [
          'Understand and integrate security in the Software Development Life Cycle (SDLC)',
          'Identify and apply security controls in software development ecosystems',
          'Assess the effectiveness of software security',
          'Assess security impact of acquired software',
          'Define and apply secure coding guidelines and standards',
        ],
      },
    ],
  },
  {
    id: 'isc2-ccsp',
    name: 'ISC2 Certified Cloud Security Professional',
    code: 'CCSP',
    provider: 'ISC2',
    level: 'Professional',
    domains: [
      {
        name: 'Cloud Concepts, Architecture, and Design',
        weight: 17,
        tasks: [
          'Understand cloud computing concepts',
          'Describe cloud reference architecture',
          'Understand security concepts relevant to cloud computing',
          'Understand design principles of secure cloud computing',
          'Evaluate cloud service providers',
        ],
      },
      {
        name: 'Cloud Data Security',
        weight: 20,
        tasks: [
          'Describe cloud data concepts',
          'Design and implement cloud data storage architectures',
          'Design and apply data security technologies and strategies',
          'Implement data discovery',
          'Implement data classification',
          'Design and implement information rights management',
          'Plan and implement data retention, deletion, and archiving policies',
          'Design and implement auditability, traceability, and accountability of data events',
        ],
      },
      {
        name: 'Cloud Platform and Infrastructure Security',
        weight: 17,
        tasks: [
          'Comprehend cloud infrastructure and platform components',
          'Design a secure data center',
          'Analyze risks associated with cloud infrastructure and platforms',
          'Plan and implement security controls',
          'Plan business continuity and disaster recovery',
        ],
      },
      {
        name: 'Cloud Application Security',
        weight: 17,
        tasks: [
          'Advocate training and awareness for application security',
          'Describe the Secure Software Development Life Cycle process',
          'Apply the Secure Software Development Life Cycle',
          'Apply cloud software assurance and validation',
          'Use verified secure software',
          'Comprehend the specifics of cloud application architecture',
          'Design appropriate identity and access management solutions',
        ],
      },
      {
        name: 'Cloud Security Operations',
        weight: 16,
        tasks: [
          'Build and implement physical and logical infrastructure for cloud environment',
          'Operate and maintain physical and logical infrastructure for cloud environment',
          'Implement operational controls and standards',
          'Support digital forensics',
          'Manage communication with relevant parties',
          'Manage security operations',
        ],
      },
      {
        name: 'Legal, Risk, and Compliance',
        weight: 13,
        tasks: [
          'Articulate legal requirements and unique risks within the cloud environment',
          'Understand privacy issues',
          'Understand audit process, methodologies, and required adaptations for a cloud environment',
          'Understand implications of cloud to enterprise risk management',
          'Understand outsourcing and cloud contract design',
        ],
      },
    ],
  },
];
