import type { CertEntry } from './types';

export const MICROSOFT_CERTS: CertEntry[] = [
  {
    id: 'az-900',
    name: 'Microsoft Azure Fundamentals',
    code: 'AZ-900',
    provider: 'Microsoft',
    level: 'Foundational',
    domains: [
      {
        name: 'Describe Cloud Concepts',
        weight: 25,
        tasks: [
          'Define cloud computing',
          'Describe the shared responsibility model',
          'Define cloud models including public, private, and hybrid',
          'Identify appropriate use cases for each cloud model',
          'Describe the consumption-based model',
          'Compare cloud pricing models',
          'Describe serverless computing',
        ],
      },
      {
        name: 'Describe Azure Architecture and Services',
        weight: 35,
        tasks: [
          'Describe the core architectural components of Azure',
          'Describe Azure regions, region pairs, and sovereign regions',
          'Describe availability zones',
          'Describe Azure datacenters',
          'Describe Azure resources and resource groups',
          'Describe subscriptions and management groups',
          'Describe Azure compute and networking services',
          'Describe Azure storage services',
          'Describe Azure identity, access, and security',
        ],
      },
      {
        name: 'Describe Azure Management and Governance',
        weight: 30,
        tasks: [
          'Describe cost management in Azure',
          'Describe features and tools in Azure for governance and compliance',
          'Describe features and tools for managing and deploying Azure resources',
          'Describe monitoring tools in Azure',
        ],
      },
    ],
  },
  {
    id: 'ai-900',
    name: 'Microsoft Azure AI Fundamentals',
    code: 'AI-900',
    provider: 'Microsoft',
    level: 'Foundational',
    domains: [
      {
        name: 'Describe Artificial Intelligence Workloads and Considerations',
        weight: 15,
        tasks: [
          'Identify features of common AI workloads',
          'Identify guiding principles for responsible AI',
        ],
      },
      {
        name: 'Describe Fundamental Principles of Machine Learning on Azure',
        weight: 20,
        tasks: [
          'Identify common machine learning techniques',
          'Describe core machine learning concepts',
          'Distinguish supervised, unsupervised, and reinforcement learning scenarios',
          'Describe model training, validation, and evaluation workflows',
          'Identify overfitting and underfitting and mitigation approaches',
          'Describe Azure Machine Learning capabilities',
        ],
      },
      {
        name: 'Describe Features of Computer Vision Workloads on Azure',
        weight: 15,
        tasks: [
          'Identify common types of computer vision solution',
          'Describe image classification, object detection, and segmentation use cases',
          'Describe OCR, document analysis, and video indexing scenarios',
          'Identify Azure tools and services for computer vision tasks',
        ],
      },
      {
        name: 'Describe Features of Natural Language Processing Workloads on Azure',
        weight: 15,
        tasks: [
          'Identify features of common NLP workload scenarios',
          'Describe sentiment analysis, key phrase extraction, and entity recognition',
          'Describe language understanding and conversational AI scenarios',
          'Identify Azure tools and services for NLP workloads',
        ],
      },
      {
        name: 'Describe Features of Generative AI Workloads on Azure',
        weight: 15,
        tasks: [
          'Identify features of generative AI solutions',
          'Identify capabilities of Azure OpenAI Service',
          'Describe prompt engineering fundamentals and context grounding patterns',
          'Describe safety, content filtering, and responsible AI controls for generative systems',
        ],
      },
    ],
  },
  {
    id: 'dp-900',
    name: 'Microsoft Azure Data Fundamentals',
    code: 'DP-900',
    provider: 'Microsoft',
    level: 'Foundational',
    domains: [
      {
        name: 'Describe Core Data Concepts',
        weight: 25,
        tasks: [
          'Describe ways to represent data',
          'Identify options for data storage',
          'Describe common data workloads',
          'Identify roles and responsibilities for data workloads',
          'Differentiate structured, semi-structured, and unstructured data patterns',
          'Compare transactional and analytical data workloads',
        ],
      },
      {
        name: 'Identify Considerations for Relational Data on Azure',
        weight: 25,
        tasks: [
          'Describe relational concepts',
          'Describe normalization and why it is used',
          'Identify common structured query language (SQL) statements',
          'Describe Azure services for relational data',
          'Describe indexing, constraints, and transaction consistency concepts',
          'Compare managed relational offerings by workload profile',
        ],
      },
      {
        name: 'Describe Considerations for Working with Non-Relational Data on Azure',
        weight: 25,
        tasks: [
          'Describe capabilities of Azure storage',
          'Describe capabilities of Azure Cosmos DB',
          'Compare key-value, document, and graph data models',
          'Describe partitioning and consistency trade-offs in globally distributed stores',
        ],
      },
      {
        name: 'Describe an Analytics Workload on Azure',
        weight: 25,
        tasks: [
          'Describe common elements of large-scale analytics',
          'Describe considerations for real-time data analytics',
          'Describe data visualization in Microsoft Power BI',
          'Describe batch and streaming pipeline components',
          'Identify semantic modeling and dashboard distribution considerations',
        ],
      },
    ],
  },
  {
    id: 'sc-900',
    name: 'Microsoft Security, Compliance, and Identity Fundamentals',
    code: 'SC-900',
    provider: 'Microsoft',
    level: 'Foundational',
    domains: [
      {
        name: 'Describe the Concepts of Security, Compliance, and Identity',
        weight: 10,
        tasks: [
          'Describe security and compliance concepts',
          'Define identity concepts',
        ],
      },
      {
        name: 'Describe the Capabilities of Microsoft Entra',
        weight: 25,
        tasks: [
          'Describe the function and identity types of Microsoft Entra ID',
          'Describe the authentication capabilities of Microsoft Entra ID',
          'Describe access management capabilities of Microsoft Entra ID',
          'Describe the identity protection and governance capabilities of Microsoft Entra',
        ],
      },
      {
        name: 'Describe the Capabilities of Microsoft Security Solutions',
        weight: 35,
        tasks: [
          'Describe core infrastructure security services in Azure',
          'Describe security management capabilities of Azure',
          'Describe security capabilities of Microsoft Sentinel',
          'Describe threat protection with Microsoft Defender XDR',
        ],
      },
      {
        name: 'Describe the Capabilities of Microsoft Compliance Solutions',
        weight: 20,
        tasks: [
          'Describe Microsoft Service Trust Portal and privacy principles',
          'Describe the compliance management capabilities of Microsoft Purview',
          'Describe information protection, data lifecycle management, and data governance capabilities of Microsoft Purview',
          'Describe the insider risk capabilities of Microsoft Purview',
          'Describe the eDiscovery and audit capabilities of Microsoft Purview',
        ],
      },
    ],
  },
  {
    id: 'az-104',
    name: 'Microsoft Azure Administrator',
    code: 'AZ-104',
    provider: 'Microsoft',
    level: 'Associate',
    domains: [
      {
        name: 'Manage Azure Identities and Governance',
        weight: 20,
        tasks: [
          'Create users and groups in Microsoft Entra ID',
          'Manage user and group properties',
          'Manage licenses in Microsoft Entra ID',
          'Manage external users',
          'Configure self-service password reset (SSPR)',
          'Manage built-in Azure roles',
          'Assign roles at different scopes',
          'Interpret access assignments',
          'Implement and manage Azure Policy',
          'Configure resource locks',
          'Apply and manage tags on resources',
          'Manage resource groups',
          'Manage subscriptions',
          'Manage costs by using alerts, budgets, and Azure Advisor recommendations',
          'Configure management groups',
        ],
      },
      {
        name: 'Implement and Manage Storage',
        weight: 15,
        tasks: [
          'Configure Azure Storage firewalls and virtual networks',
          'Create and use shared access signature (SAS) tokens',
          'Configure stored access policies',
          'Manage access keys',
          'Configure identity-based access for Azure Files',
          'Create and configure storage accounts',
          'Configure Azure Storage redundancy',
          'Configure object replication',
          'Configure storage account encryption',
          'Manage data by using Azure Storage Explorer and AzCopy',
          'Create and configure a file share in Azure Storage',
          'Create and configure a container in Blob Storage',
          'Configure storage tiers',
          'Configure soft delete for blobs and containers',
          'Configure snapshots and soft delete for Azure Files',
          'Configure blob lifecycle management',
          'Configure blob versioning',
        ],
      },
      {
        name: 'Deploy and Manage Azure Compute Resources',
        weight: 20,
        tasks: [
          'Interpret an Azure Resource Manager template or a Bicep file',
          'Modify an existing Azure Resource Manager template',
          'Modify an existing Bicep file',
          'Deploy resources by using an Azure Resource Manager template or a Bicep file',
          'Export a deployment as an Azure Resource Manager template or convert to a Bicep file',
          'Create a virtual machine',
          'Configure Azure Disk Encryption',
          'Move a virtual machine to another resource group, subscription, or region',
          'Manage virtual machine sizes',
          'Manage virtual machine disks',
          'Deploy virtual machines to availability zones and availability sets',
          'Deploy and configure Azure Virtual Machine Scale Sets',
          'Create and manage an Azure container registry',
          'Provision a container by using Azure Container Instances',
          'Provision a container by using Azure Container Apps',
          'Manage sizing and scaling for containers, including Azure Container Instances and Azure Container Apps',
          'Provision an App Service plan',
          'Configure scaling for an App Service plan',
          'Create an App Service',
          'Configure certificates and Transport Layer Security (TLS) for an App Service',
          'Map an existing custom DNS name to an App Service',
          'Configure backup for an App Service',
          'Configure networking settings for an App Service',
          'Configure deployment slots for an App Service',
        ],
      },
      {
        name: 'Implement and Manage Virtual Networking',
        weight: 15,
        tasks: [
          'Create and configure virtual networks and subnets',
          'Create and configure virtual network peering',
          'Configure public IP addresses',
          'Configure user-defined network routes',
          'Troubleshoot network connectivity',
          'Create and configure network security groups (NSGs) and application security groups',
          'Evaluate effective security rules in NSGs',
          'Implement Azure Bastion',
          'Configure service endpoints for Azure platform as a service (PaaS)',
          'Configure private endpoints for Azure PaaS',
          'Configure Azure DNS',
          'Configure an internal or public load balancer',
          'Troubleshoot load balancing',
        ],
      },
      {
        name: 'Monitor and Maintain Azure Resources',
        weight: 10,
        tasks: [
          'Interpret metrics in Azure Monitor',
          'Configure log settings in Azure Monitor',
          'Query and analyze logs in Azure Monitor',
          'Set up alert rules, action groups, and alert processing rules in Azure Monitor',
          'Configure and interpret monitoring of virtual machines, storage accounts, and networks by using Azure Monitor Insights',
          'Use Azure Network Watcher and Connection Monitor',
          'Create a Recovery Services vault',
          'Create an Azure Backup vault',
          'Create and configure a backup policy',
          'Perform backup and restore operations by using Azure Backup',
          'Configure Azure Site Recovery for Azure resources',
          'Perform a failover to a secondary region by using Site Recovery',
          'Configure and interpret reports and alerts for backups',
        ],
      },
    ],
  },
  {
    id: 'pl-300',
    name: 'Microsoft Power BI Data Analyst',
    code: 'PL-300',
    provider: 'Microsoft',
    level: 'Associate',
    domains: [
      {
        name: 'Prepare the Data',
        weight: 25,
        tasks: [
          'Get data from relational and non-relational sources',
          'Profile data and identify data quality issues',
          'Clean, transform, and load data by using Power Query',
          'Design data loading strategies and storage modes',
          'Configure incremental refresh and dataflows',
        ],
      },
      {
        name: 'Model the Data',
        weight: 25,
        tasks: [
          'Design and build a star schema data model',
          'Create and optimize model relationships',
          'Create DAX measures and calculated columns',
          'Apply row-level security and object-level security',
          'Improve model performance and usability',
        ],
      },
      {
        name: 'Visualize and Analyze the Data',
        weight: 30,
        tasks: [
          'Design effective report layouts and navigation',
          'Create and configure visuals for analytical storytelling',
          'Apply filters, slicers, and drill-through behavior',
          'Implement dynamic visuals with DAX and parameters',
          'Use AI visuals and quick insights for deeper analysis',
        ],
      },
      {
        name: 'Deploy and Maintain Assets',
        weight: 20,
        tasks: [
          'Manage workspaces, semantic models, and reports',
          'Configure scheduled refresh and gateway connections',
          'Implement deployment pipelines and app distribution',
          'Monitor usage, performance, and refresh reliability',
          'Apply governance, sensitivity labels, and lifecycle controls',
        ],
      },
    ],
  },
  {
    id: 'az-204',
    name: 'Microsoft Azure Developer',
    code: 'AZ-204',
    provider: 'Microsoft',
    level: 'Associate',
    domains: [
      {
        name: 'Develop Azure Compute Solutions',
        weight: 25,
        tasks: [
          'Implement containerized solutions',
          'Implement Azure App Service Web Apps',
          'Implement Azure Functions',
          'Implement durable workflows and event-driven compute patterns',
          'Implement API endpoints and background processing for cloud-native apps',
        ],
      },
      {
        name: 'Develop for Azure Storage',
        weight: 15,
        tasks: [
          'Develop solutions that use Azure Cosmos DB',
          'Develop solutions that use Azure Blob Storage',
          'Implement data lifecycle, versioning, and retention strategies',
          'Implement secure data access with managed identities and key vault integration',
        ],
      },
      {
        name: 'Implement Azure Security',
        weight: 20,
        tasks: [
          'Implement user authentication and authorization',
          'Implement secure Azure solutions',
          'Implement token-based access to Azure resources and downstream APIs',
          'Implement secret rotation and secure configuration management',
        ],
      },
      {
        name: 'Monitor, Troubleshoot, and Optimize Azure Solutions',
        weight: 15,
        tasks: [
          'Implement caching for solutions',
          'Troubleshoot solutions by using Application Insights',
          'Implement distributed tracing and telemetry correlation',
          'Optimize application performance, resiliency, and cost characteristics',
        ],
      },
      {
        name: 'Connect to and Consume Azure Services and Third-party Services',
        weight: 15,
        tasks: [
          'Implement API Management',
          'Develop event-based solutions',
          'Develop message-based solutions',
          'Implement secure service-to-service integration patterns',
          'Integrate external services with resilient retry and dead-letter handling',
        ],
      },
    ],
  },
  {
    id: 'az-305',
    name: 'Microsoft Azure Solutions Architect Expert',
    code: 'AZ-305',
    provider: 'Microsoft',
    level: 'Expert',
    domains: [
      {
        name: 'Design Identity, Governance, and Monitoring Solutions',
        weight: 25,
        tasks: [
          'Design solutions for logging and monitoring',
          'Design authentication and authorization solutions',
          'Design governance solutions',
          'Design identity lifecycle and privileged access governance',
          'Design policy, compliance, and operational guardrail frameworks',
        ],
      },
      {
        name: 'Design Data Storage Solutions',
        weight: 20,
        tasks: [
          'Design data storage solutions for relational data',
          'Design data storage solutions for non-relational data',
          'Design data integration solutions',
          'Design data protection, encryption, and key management strategies',
          'Design data classification, retention, and compliance-aware architectures',
        ],
      },
      {
        name: 'Design Business Continuity Solutions',
        weight: 15,
        tasks: [
          'Design solutions for backup and disaster recovery',
          'Design for high availability',
          'Design failover, failback, and regional resiliency strategies',
          'Design recovery objectives and validation testing plans',
        ],
      },
      {
        name: 'Design Infrastructure Solutions',
        weight: 30,
        tasks: [
          'Design compute solutions',
          'Design application architecture solutions',
          'Design network solutions',
          'Design migrations',
          'Design hybrid and multiregion network topologies',
          'Design modernization paths for legacy workloads',
        ],
      },
    ],
  },
  {
    id: 'az-400',
    name: 'Microsoft DevOps Engineer Expert',
    code: 'AZ-400',
    provider: 'Microsoft',
    level: 'Expert',
    domains: [
      {
        name: 'Configure Processes and Communications',
        weight: 10,
        tasks: [
          'Configure activity traceability and flow of work',
          'Configure collaboration and communication',
          'Define team workflows, reporting cadences, and governance checkpoints',
          'Establish visibility for cross-team dependencies and release readiness',
        ],
      },
      {
        name: 'Design and Implement Source Control',
        weight: 15,
        tasks: [
          'Design and implement a source control strategy',
          'Plan and implement branching strategies for the source code',
          'Configure and manage repositories',
          'Implement pull request policies and branch protection controls',
          'Design repository structures for mono-repo and multi-repo delivery models',
        ],
      },
      {
        name: 'Design and Implement Build and Release Pipelines',
        weight: 40,
        tasks: [
          'Design and implement pipeline automation',
          'Design and implement a package management strategy',
          'Design and implement pipelines for infrastructure as code',
          'Design and implement a deployment strategy',
          'Design testing gates, quality checks, and progressive deployment controls',
          'Implement rollback and environment promotion strategies across stages',
        ],
      },
      {
        name: 'Develop a Security and Compliance Plan',
        weight: 10,
        tasks: [
          'Design and implement authentication and authorization methods',
          'Design and implement a strategy for managing sensitive information in automation',
          'Implement supply chain security controls for code, packages, and build agents',
          'Design compliance evidence collection and policy enforcement automation',
        ],
      },
      {
        name: 'Implement an Instrumentation Strategy',
        weight: 10,
        tasks: [
          'Configure monitoring for a DevOps environment',
          'Analyze metrics from instrumentation',
          'Design observability dashboards for service reliability objectives',
          'Implement alert routing and incident response integration',
        ],
      },
    ],
  },
];
